Mathematical and Statistical Programming with NumPy

In [2]:
import numpy as np

In [4]:
x= np.arange(10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#1. Display the first 5 elements;
print(x[0:5:1])

[0 1 2 3 4]


In [19]:
#2. Display every other element:
print(x[0:-1:2])

[0 2 4 6 8]


In [29]:
#3. Display the elements from index 5 in reverse order:
print(x[-1:4:-1])

[9 8 7 6 5]


In [37]:
y = np.array([[12, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])


In [39]:
#4. Display the first 2 rows and first 3 columns
y[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [45]:
#5. Display first colmn of y:

y[:,0]

array([12,  7,  1])

In [49]:
#6.Displau first row of y:

y[0,:]

array([12,  5,  2,  4])

In [61]:
#7.real cdc_1 file into notebook
data = np.genfromtxt(r"C:\Users\Admin\Documents\Course Files\QADHPYTHON\data\cdc_1.csv", delimiter = ',', skip_header = 1)

In [63]:
#8. Calculations:
data
height = data[:,0]
weight = data[:,1]
age = data[:,2]
minimums = {"height": min(height), "weight":min(weight), "age":min(age)}
maximums = {"height":max(height), "weight":max(weight), "age":max(age)}
column_length = len(height)
means = {"height":sum(height)/column_length, "weight":sum(weight)/column_length, "age":sum(age)/column_length}


array([[ 70., 175.,  77.],
       [ 71., 194.,  31.],
       [ 67., 170.,  45.],
       ...,
       [ 69., 224.,  73.],
       [ 73., 200.,  35.],
       [ 69., 170.,  83.]])

Descriptive Statistics with NumPy

In [90]:
#1. Read in cnc_nan.csv

import scipy.stats

data =np.genfromtxt(r"C:\Users\Admin\Documents\Course Files\QADHPYTHON\data\cdc_nan.csv", delimiter = ',', skip_header = 1)

In [97]:
#2. Separate heights and weights column
heights = data[:,0]
weights = data[:,1]