Mathematical and Statistical Programming with NumPy

In [2]:
import numpy as np

In [3]:
x= np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#1. Display the first 5 elements;
print(x[0:5:1])

[0 1 2 3 4]


In [6]:
#2. Display every other element:
print(x[0:-1:2])

[0 2 4 6 8]


In [7]:
#3. Display the elements from index 5 in reverse order:
print(x[-1:4:-1])

[9 8 7 6 5]


In [8]:
y = np.array([[12, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])


In [9]:
#4. Display the first 2 rows and first 3 columns
y[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [10]:
#5. Display first colmn of y:

y[:,0]

array([12,  7,  1])

In [11]:
#6.Displau first row of y:

y[0,:]

array([12,  5,  2,  4])

In [12]:
#7.real cdc_1 file into notebook
data = np.genfromtxt(r"C:\Users\Admin\Documents\Course Files\QADHPYTHON\data\cdc_1.csv", delimiter = ',', skip_header = 1)

In [13]:
#8. Calculations:
data
height = data[:,0]
weight = data[:,1]
age = data[:,2]
minimums = {"height": min(height), "weight":min(weight), "age":min(age)}
maximums = {"height":max(height), "weight":max(weight), "age":max(age)}
column_length = len(height)
means = {"height":sum(height)/column_length, "weight":sum(weight)/column_length, "age":sum(age)/column_length}


Descriptive Statistics with NumPy

In [14]:
#1. Read in cnc_nan.csv

import scipy.stats

data =np.genfromtxt(r"C:\Users\Admin\Documents\Course Files\QADHPYTHON\data\cdc_nan.csv", delimiter = ',', skip_header = 1)

In [15]:
#2. Separate heights and weights column
heights = data[:,0]
weights = data[:,1]

Univariate

Measures of Central Tendancy

In [32]:
#1
median_heights = np.median(heights)
print(f"The median height is: {median_heights}")

The median height is: 70.0


In [33]:
median_weights = np.median(weights)
print(f"The median weight is: {median_weights}") # suggesting this has missing values

The median weight is: nan


In [34]:
#2 checking for missing values
total_nan_heights = np.sum(np.isnan(heights)) #showing why we were able to calculate median
print(f"The number of missing values in Heights are: {total_nan_heights} ")

The number of missing values in Heights are: 0 


In [36]:
total_nan_weights = np.sum(np.isnan(weights))
print(f"The number of missing values in Weights are: {total_nan_weights}")

The number of missing values in Weights are: 3


In [37]:
#3 positions of missing values
nan_positions_weights = np.where(np.isnan(weights))
print(f"The positions of the missing values in weights are: {nan_positions_weights}")

The positions of the missing values in weights are: (array([ 3, 11, 17]),)


In [38]:
#4
median_weight_clean = np.nanmedian(weights)
print(f"The median weights after removing missing values is: {median_weight_clean}")

The median weights after removing missing values is: 185.0


Mean

In [43]:
mean_height = np.mean(heights)
print(f"The mean value of Heights is: {mean_height}")

The rounded mean value of Heights is: 70.25164594001463


In [44]:
mean_weight = np.nanmean(weights)
print(f"The mean value of Weights is: {mean_weight} ")

The mean value of Weights is: 189.3251097637466 


Measures of Spread (variability)

Range

In [60]:
range_heights = int(np.nanmax(heights)-np.nanmin(heights))
print(f"The range of the heights is: {range_heights}")

The range of the heights is: 44


In [61]:
range_weights = int(np.nanmax(weights) - np.nanmin(weights))
print(f"The range of the weights is: {range_weights}")

The range of the weights is: 422


In [66]:
height_upper_quartile = int(np.nanpercentile(heights, 75))
height_lower_quartile = int(np.nanpercentile(heights, 25))
heights_IQR = int(height_upper_quartile - height_lower_quartile)
print(f"The lower and upper quartiles of Heights are {height_lower_quartile} and {height_upper_quartile}.\nThus, the interquartile range is {heights_IQR }.")

The lower and upper quartiles of Heights are 68 and 72.
Thus, the interquartile range is 4.


In [67]:
weight_upper_quartile = int(np.nanpercentile(weight, 75))
weight_lower_quartile = int(np.nanpercentile(weights, 25))
weights_IQR = int(weight_upper_quartile - weight_lower_quartile)
print(f"The lower and upper quartiles of weights are {weight_lower_quartile} and {weight_upper_quartile}.\nThus, the interquartile range is {weights_IQR }.")

The lower and upper quartiles of weights are 165 and 210.
Thus, the interquartile range is 45.


Variance

In [74]:
population_variance_height = round(np.nanvar(heights),4)
sample_variance_height = round(np.nanvar(heights, ddof=1), 4)
print(f"The rounded population and sample variance of the Heights are: {population_variance_height} and {sample_variance_height}.")

The rounded population and sample variance of the Heights are: 9.0545 and 9.0554.


In [75]:
population_variance_weight = round(np.nanvar(weights),4)
sample_variance_weight = round(np.nanvar(weights, ddof=1), 4)
print(f"The rounded population and sample variance of the Weights are: {population_variance_weight} and {sample_variance_weight}.")

The rounded population and sample variance of the Weights are: 1336.1876 and 1336.3273.


Standard Deviation

In [78]:
population_std_height = round(population_variance_height**(0.5),4)
sample_std_height = round(sample_variance_height**(0.5), 4)
population_std_weight = round(population_variance_weight**(0.5),4)
sample_std_weight = round(sample_variance_weight**(0.5),4)

In [79]:
print(f"The rounded population and sample standard deviation of the Heights are: {population_std_height} and {sample_std_height}.")

The rounded population and sample standard deviation of the Heights are: 3.0091 and 3.0092.


In [80]:
print(f"The rounded population and sample standard deviation of the Weights are: {population_std_weight} and {sample_std_weight}.")

The rounded population and sample standard deviation of the Weights are: 36.5539 and 36.5558.


Bivariate

Covariance

In [104]:
covariance = np.cov(heights,weights, ddof=1)  #this cannot be calculated given the missing values therefore let us clean the data
weights_cleaned = weights[~np.isnan(weights)]
length_weights = len(weights_cleaned)
length_heights=len(heights)
print(f"The lenghth of the heights and weights arrays are: {length_heights} & {length_weights}.")
#we note that heights is larger since we cleaned the wreights set
#hence, make the legnths equivalent by randomly removign 3 points
randompoints = np.random.choice (heights.size, size = 3, replace=False)
heights_shortened = np.delete(heights, randompoints)
length_heights_shortened = len(heights_shortened)
print(f"So, now the legnth of the heights array is {length_heights_shortened}")
#now we can fairly calculate the covariance:
covariance_cleaned = np.cov(heights_shortened, weights_cleaned, ddof=1)
print(f"The Covariance between the adjusted Heights and Weights are: \n{covariance_cleaned}")

The lenghth of the heights and weights arrays are: 9569 & 9566.
So, now the legnth of the heights array is 9566
The Covariance between the adjusted Heights and Weights are: 
[[   9.04833427    5.53401567]
 [   5.53401567 1336.32732971]]


In [121]:
print(f"The Left diagonal values are the variance figures we have calculated before and the right diagonal value show the covariance between height and weight. \nShowing that as one increase in POSITIVE DIRECTION, the other will also INCREASES linearly in a POSITIVE DIRECTION, with a STRENGTH of 5.\nThe strength is harder to interpret for covariance since it is not a scaled value unlike correlaiton.")

The Left diagonal values are the variance figures we have calculated before and the right diagonal value show the covariance between height and weight. 
Showing that as one increase in POSITIVE DIRECTION, the other will also INCREASES linearly in a POSITIVE DIRECTION, with a STRENGTH of 5.
The strength is harder to interpret for covariance since it is not a scaled value unlike correlaiton.


Correlation

We shall use the adjusted arrays for height and weight to circumvent the NaN and dimension issue.

In [122]:
correlation_cleaned = np.corrcoef(heights_shortened, weights_cleaned)
print(f"The Correlation between the adjusted Heights and Weights are: \n{correlation_cleaned}.")

The Correlation between the adjusted Heights and Weights are: 
[[1.         0.05032684]
 [0.05032684 1.        ]].


In [123]:
print(f"1.Ignore both values of 1 on the left diagonal as the correlation of a dataset with itself will always be 1. \n2.The values along the right diagonal are equivalent since the correlation is symmetric.\n3.The value indicates that if one variance, height or weight, increases, the other will also icnrease with a strength of 0.05.")

1.Ignore both values of 1 on the left diagonal as the correlation of a dataset with itself will always be 1. 
2.The values along the right diagonal are equivalent since the correlation is symmetric.
3.The value indicates that if one variance, height or weight, increases, the other will also icnrease with a strength of 0.05.
